#include <iostream>

#include <glad/glad.h>

#include "Mesh.h"

#include <assimp/scene.h>
#include <assimp/Importer.hpp>
#include <assimp/postprocess.h>

#define STB_IMAGE_IMPLEMENTATION
#include <stb/stb_image.h>

#include "Grid.h"
#include "Octree.h"

Mesh::Mesh()
{
}

Mesh::~Mesh()
{
}

void Mesh::init(std::string path, GLuint id)
{
    shaderId = id;
    loadModel(path);
    initBuffer();
}

void Mesh::initSpatial(bool useOctree, glm::mat4 mat)
{
    if (useOctree)
        pSpatial = std::make_unique<Octree>();
    else
        pSpatial = std::make_unique<Grid>(glm::ivec3(16));

    pSpatial->Build(vertices, indices, mat);
}

void Mesh::loadModel(std::string path)
{
    // IMPORTANT: clear previous data (in case same Mesh object reused)
    vertices.clear();
    indices.clear();
    textures.clear();
    buffers.clear();

    Assimp::Importer importer;

    // FIXES:
    // - Triangulate faces (OBJ often has quads/ngons)
    // - Generate normals if missing
    // - Flip UVs for consistency with your previous assets
    const aiScene* scene = importer.ReadFile(
        path,
        aiProcess_Triangulate |
        aiProcess_JoinIdenticalVertices |
        aiProcess_FlipUVs |
        aiProcess_GenSmoothNormals
    );

    if (!scene || !scene->mRootNode || scene->mNumMeshes == 0)
    {
        std::cout << "load model failed: " << path << std::endl;
        std::cout << "Assimp error: " << importer.GetErrorString() << std::endl;
        return;
    }

    std::cout << "load model successful: " << path << std::endl;

    Vertex v;

    // at the moment we only handle one mesh, but your loop supports multiple
    for (unsigned int i = 0; i < scene->mNumMeshes; i++)
    {
        aiMesh* mesh = scene->mMeshes[i];
        if (!mesh) continue;

        int nVertex = (int)mesh->mNumVertices;

        for (int j = 0; j < nVertex; j++)
        {
            // position
            glm::vec3 pos;
            pos.x = mesh->mVertices[j].x;
            pos.y = mesh->mVertices[j].y;
            pos.z = mesh->mVertices[j].z;
            v.pos = pos;

            // normal (OBJ may not have normals -> generated by GenSmoothNormals, but guard anyway)
            glm::vec3 normal(0.0f, 1.0f, 0.0f);
            if (mesh->HasNormals())
            {
                normal.x = mesh->mNormals[j].x;
                normal.y = mesh->mNormals[j].y;
                normal.z = mesh->mNormals[j].z;
            }
            v.normal = normal;

            // texture coords
            if (mesh->mTextureCoords[0])
            {
                glm::vec2 uv;
                uv.x = mesh->mTextureCoords[0][j].x;
                uv.y = mesh->mTextureCoords[0][j].y;
                v.texCoord = uv;
            }
            else
            {
                v.texCoord = glm::vec2(0.0f, 0.0f);
            }

            vertices.push_back(v);
        }

        // indices (SAFE: use mNumIndices, NOT fixed 3)
        int nFaces = (int)mesh->mNumFaces;
        for (int j = 0; j < nFaces; j++)
        {
            const aiFace& face = mesh->mFaces[j];
            for (unsigned int k = 0; k < face.mNumIndices; k++)
            {
                indices.push_back(face.mIndices[k]);
            }
        }
    }

    // material/texture (only for first mesh, same as before)
    aiMesh* firstMesh = scene->mMeshes[0];

    if (firstMesh && firstMesh->mMaterialIndex >= 0)
    {
        std::string dir = "";
        const size_t last_slash_idx = path.rfind('/');
        if (std::string::npos != last_slash_idx)
        {
            dir = path.substr(0, last_slash_idx);
        }

        aiMaterial* material = scene->mMaterials[firstMesh->mMaterialIndex];
        if (material)
        {
            std::vector<Texture> diffuseMaps = loadMaterialTextures(
                material,
                aiTextureType_DIFFUSE,
                "texture_diffuse",
                dir
            );
            textures.insert(textures.end(), diffuseMaps.begin(), diffuseMaps.end());
        }
    }

    // debug
    std::cout << "numVertex: " << vertices.size() << std::endl;
    std::cout << "numIndex: " << indices.size() << std::endl;
}

void Mesh::initBuffer()
{
    // create vertex buffer
    GLuint vao;
    glGenVertexArrays(1, &vao);

    GLuint vertBufID;
    glGenBuffers(1, &vertBufID);

    GLuint idxBufID;
    glGenBuffers(1, &idxBufID);

    // remember VAO
    glBindVertexArray(vao);
    buffers.push_back(vao);

    // vertex buffer
    glBindBuffer(GL_ARRAY_BUFFER, vertBufID);
    glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(Vertex), &vertices[0], GL_STATIC_DRAW);

    glEnableVertexAttribArray(0);
    glVertexAttribPointer(0, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), 0);

    // normal attributes
    glEnableVertexAttribArray(1);
    glVertexAttribPointer(1, 3, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)(sizeof(float) * 3));

    // texture coord attribute
    glEnableVertexAttribArray(2);
    glVertexAttribPointer(2, 2, GL_FLOAT, GL_FALSE, sizeof(Vertex), (void*)offsetof(Vertex, texCoord));

    // index buffer
    glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, idxBufID);
    glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(GLuint), indices.data(), GL_STATIC_DRAW);

    glBindVertexArray(0);
}

void Mesh::setShaderId(GLuint sid)
{
    shaderId = sid;
}

// =====================================================
std::vector<Texture> Mesh::loadMaterialTextures(aiMaterial* mat, aiTextureType type, std::string typeName, std::string dir)
{
    std::vector<Texture> textures;

    int nTex = mat->GetTextureCount(type);
    for (unsigned int i = 0; i < (unsigned int)nTex; i++)
    {
        aiString str;
        mat->GetTexture(type, i, &str);

        Texture texture;
        texture.id = loadTextureAndBind(str.C_Str(), dir);
        texture.type = typeName;
        if (texture.id > 0)
            textures.push_back(texture);
    }
    return textures;
}

void Mesh::setUseMipmaps(bool enabled)
{
    for (auto& t : textures)
    {
        glBindTexture(GL_TEXTURE_2D, t.id);

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);

        if (enabled)
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR_MIPMAP_LINEAR);
        else
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

        glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
    }

    glBindTexture(GL_TEXTURE_2D, 0);
}

unsigned int Mesh::loadTextureAndBind(const char* path, const std::string& directory)
{
    std::string filename = std::string(path);
    filename = directory + '/' + filename;

    int width, height, nrComponents;
    unsigned char* data = stbi_load(filename.c_str(), &width, &height, &nrComponents, 0);
    if (!data)
    {
        std::cout << "Texture failed to load at path: " << path << std::endl;
        stbi_image_free(data);
        return 0;
    }

    unsigned int textureID;
    glGenTextures(1, &textureID);

    GLenum format;
    if (nrComponents == 1)
        format = GL_RED;
    else if (nrComponents == 3)
        format = GL_RGB;
    else
        format = GL_RGBA;

    glActiveTexture(GL_TEXTURE0);
    glBindTexture(GL_TEXTURE_2D, textureID);

    glTexImage2D(GL_TEXTURE_2D, 0, format, width, height, 0, format, GL_UNSIGNED_BYTE, data);

    // You can still generate mipmaps, but default filtering is NO mipmaps (GL_LINEAR)
    glGenerateMipmap(GL_TEXTURE_2D);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_REPEAT);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);

    stbi_image_free(data);

    return textureID;
}

Material Mesh::loadMaterial(aiMaterial* mat)
{
    Material material;
    aiColor3D color(0.f, 0.f, 0.f);
    float shininess;

    mat->Get(AI_MATKEY_COLOR_DIFFUSE, color);
    material.Diffuse = glm::vec3(color.r, color.b, color.g);

    mat->Get(AI_MATKEY_COLOR_AMBIENT, color);
    material.Ambient = glm::vec3(color.r, color.b, color.g);

    mat->Get(AI_MATKEY_COLOR_SPECULAR, color);
    material.Specular = glm::vec3(color.r, color.b, color.g);

    mat->Get(AI_MATKEY_SHININESS, shininess);
    material.Shininess = shininess;

    return material;
}

// =====================================================

// all drawings come here
void Mesh::draw(glm::mat4 matModel, glm::mat4 matView, glm::mat4 matProj)
{
    glUseProgram(shaderId);

    GLuint model_loc = glGetUniformLocation(shaderId, "model");
    glUniformMatrix4fv(model_loc, 1, GL_FALSE, &matModel[0][0]);

    GLuint view_loc = glGetUniformLocation(shaderId, "view");
    glUniformMatrix4fv(view_loc, 1, GL_FALSE, &matView[0][0]);

    GLuint projection_loc = glGetUniformLocation(shaderId, "projection");
    glUniformMatrix4fv(projection_loc, 1, GL_FALSE, &matProj[0][0]);

    GLint textureLoc = glGetUniformLocation(shaderId, "textureMap");
    glUniform1i(textureLoc, 0);

    if (!textures.empty())
    {
        glActiveTexture(GL_TEXTURE0);
        glBindTexture(GL_TEXTURE_2D, textures[0].id);
    }

    glUniform1i(glGetUniformLocation(shaderId, "bPicked"), bPicked);

    glBindVertexArray(buffers[0]);
    glDrawElements(GL_TRIANGLES, (GLsizei)indices.size(), GL_UNSIGNED_INT, 0);
    glBindVertexArray(0);
}
